name: CI-CD

# only run on pushes to main or pull requests
on:
  push:
    # push to any branch *
    branches: [main]
  pull_request:
    branches: [main, development]

jobs:
  ################################################################################################
  # Unit-Tests: Run unit tests using pytest
  ################################################################################################
  Unit-Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15 # Consider increasing timeout
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14] # , windows-latest removed for now
        env: ["py310", "py311", "py312"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ${{ matrix.env }}
          pixi-version: v0.33.0
          cache: true
          locked: false # wont be the same because of the tag

      - name: Run pytest
        run: |
          pixi run -e ${{ matrix.env }} test

      # - name: Upload coverage report artifact to be used by Codecov
      #   # only upload if matrix.os is ubuntu-latest and matrix.python-version is 3.12
      #   if: matrix.os == 'ubuntu-latest'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-report
      #     path: coverage-report